common/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.gis import admin
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from massnahmen.views import IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('jsi18n/', cache_page(86400, key_prefix='jsi18n-1')(JavaScriptCatalog.as_view()),
         name='javascript-catalog'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('unterhalt/', include('unterhalt.urls')),
    path('waldrand/', include('waldrand.urls')),
    path('public/', include('public.urls')),
    path('', include('massnahmen.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

massnahmen/models.py
from django.contrib.gis.db import models as gis_models
from django.urls import reverse
from django.db import models


class Eigentuemer(models.Model):
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True)
    name = models.TextField(db_column='eigentuemer')

    class Meta:
        db_table = 'lt_eigentuemer'

    def __str__(self):
        return self.name


class GemeindeBL(gis_models.Model):
    gid         = models.AutoField(primary_key=True)
    geom_id     = models.IntegerField(null=True, blank=True, db_column='GEOM_ID')
    name        = models.CharField(max_length=64, null=True, blank=True, db_column='GEM_NAME')
    genauigkeit = models.CharField(max_length=64, null=True, blank=True, db_column='GENAUIGKEI')
    gemeinde_i  = models.IntegerField(null=True, blank=True, db_column='GEMEINDE_I', unique=True)
    gem_nr_alt  = models.IntegerField(null=True, blank=True, db_column='GEM_NR_ALT', unique=True, db_index=True)
    gem_nr_a_1  = models.IntegerField(null=True, blank=True, db_column='GEM_NR_A_1')
    bezirk_id   = models.IntegerField(null=True, blank=True, db_column="BEZIRK_ID_")
    bezirk_name = models.CharField(max_length=64, null=True, blank=True, db_column='BEZIRK_NAM')
    wep         = models.IntegerField(null=True, blank=True, db_column="WEP")
    the_geom    = gis_models.PolygonField(srid=2056, null=True, blank=True)

    class Meta:
        db_table = 'Gemeinden_BL'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Baumart(models.Model):
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True)
    baumart = models.CharField(max_length=250)

    class Meta:
        db_table = 'lt_baumarten'

    def __str__(self):
        return self.baumart.strip()


class EingriffsJahr(models.Model):
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True)
    jahr = models.TextField()

    class Meta:
        db_table = 'lt_eingriffsjahr'

    def __str__(self):
        return self.jahr


class Pflanzung(gis_models.Model):
    lokalname = models.TextField(blank=True)
    realisiert = models.IntegerField(null=True, db_column='pflanzungsdatum_realisiert')
    realisiert_jahre = models.ForeignKey(EingriffsJahr, blank=True, null=True,
        related_name='pflanzungen',
        verbose_name="Geschäftsjahr realisiert", on_delete=models.CASCADE)
    eigentuemer = models.ForeignKey(Eigentuemer, null=True, db_column='eigentum',
        on_delete=models.CASCADE)
    zaunlaenge = models.IntegerField(default=0, help_text="Länge das Zauns in Meter")
    bemerkungen = models.TextField(blank=True, db_column='bemerkungen_besonderes')
    geom = gis_models.PolygonField(srid=2056)
    baumarten_list = models.ManyToManyField(Baumart, through='PflanzungBaumart')

    class Meta:
        db_table = 'pflanzflaechen'

    def __str__(self):
        value = self.eigentuemer.name if self.eigentuemer else '<kein eigentümer>'
        if self.lokalname:
            value = "%s (%s)" % (value, self.lokalname)
        return value

    def get_absolute_url(self):
        return reverse('pflanzung_detail', args=[self.pk])

    @property
    def title(self):
        return 'Pflanzung; %s (%s) - %s' % (
            self.lokalname, self.realisiert or '-', self.eigentuemer
        )


class PflanzungBaumart(models.Model):
    pflanzung = models.ForeignKey(Pflanzung, db_column='pflae_id', on_delete=models.CASCADE)
    baumart = models.ForeignKey(Baumart, db_column='baumart', on_delete=models.CASCADE)
    anzahl = models.IntegerField(null=True)
    provenienz = models.TextField(blank=True)
    abstand_x = models.IntegerField(null=True, db_column='pflanzabstand x')
    abstand_y = models.IntegerField(null=True, db_column='pflanzabstand y')
    einzelschutz = models.IntegerField(null=True),
    bemerkungen = models.TextField(blank=True, db_column='bemerkungen_besonderes')

    class Meta:
        db_table = 'pflanzung_baumarten'

    def __str__(self):
        return "%s in %s (x:%s, y:%s)" % (
            self.baumart, self.pflanzung, self.abstand_x or '-', self.abstand_y or '-')


class MassnahmeTyp(models.Model):
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True)
    name = models.TextField(db_column='name_massnahme')

    class Meta:
        db_table = 'lt_massnahme'

    def __str__(self):
        return self.name


class NaturschutzMassnahme(models.Model):
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True)
    name = models.TextField(db_column='massnahme')
    ziel = models.TextField(blank=True)

    class Meta:
        db_table = 'lt_naturschutzmassnahme'

    def __str__(self):
        return self.name


class Planung(gis_models.Model): # Rename to Holzschlag?
    QUARTAL_CHOICES = (
        (2, 'Apr-Jun (Q2)'),
        (3, 'Jul-Sep (Q3)'),
        (4, 'Okt-Dez (Q4)'),
        (1, 'Jan-März (Q1)'),
    )
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True, null=True, blank=True)
    typ = models.ForeignKey(MassnahmeTyp, db_column='Massnahmen', verbose_name="Massnahme",
        on_delete=models.CASCADE)
    lokalname = models.CharField(max_length=255, blank=True)
    geschaetzt = models.IntegerField(null=True, verbose_name="Holzvolumen geschätzt (sv)")
    bemerkunge = models.CharField(max_length=255, blank=True, verbose_name="Bemerkungen")
    beschreibung = models.CharField(max_length=255, blank=True, verbose_name="Beschreibung (Grund/Ziel)")
    eingriffsz = models.CharField(max_length=255, blank=True, db_column='Eingriffsz', verbose_name="Eingriffsziel")
    the_geom = gis_models.PolygonField(srid=2056)
    eigentuemer = models.ForeignKey(Eigentuemer, null=True, db_column='eigentuemer',
        on_delete=models.CASCADE)
    zwangsnutzung = models.BooleanField(null=True, default=False)
    waldbewirtschaftung = models.BooleanField(null=True, default=False)
    sicherheitseingriff = models.BooleanField(null=True, default=False)
    schlagvorbereitung = models.BooleanField(null=True, default=False)
    naturschutzmassnahme = models.ForeignKey(NaturschutzMassnahme, blank=True, null=True,
        db_column='naturschutzmassnahme',on_delete=models.CASCADE)
    geplant = models.ForeignKey(EingriffsJahr, blank=True, null=True,
        db_column='eingriffsjahr_geplant', related_name='geplant_planung',
        verbose_name="Massnahme geplant", on_delete=models.CASCADE)
    quartal_geplant = models.SmallIntegerField(null=True, blank=True, choices=QUARTAL_CHOICES)
    ausgefuehrt = models.IntegerField(blank=True, null=True,
        db_column='eingriffsjahr_ausgefuehrt', verbose_name="Massnahme ausgeführt")
    schlagchef = models.TextField()
    arbeitsauftrag = models.TextField()

    class Meta:
        db_table = 'massnahmenplanung'

    def __str__(self):
        if self.id:
            return "%s (%s)" % (self.lokalname, self.id)
        else:
            return self.lokalname or str(self.gid)

    @property
    def title(self):
        return "%s: %s (%s); %s" % (
            self.typ, self.__str__(), self.geplant or '-', self.eigentuemer or '')

    @property
    def naturschutz(self):
        return bool(self.naturschutzmassnahme_id)

    def get_absolute_url(self):
        return reverse('planung_detail', args=[self.pk])


class PflegeTyp(models.Model):
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True)
    pflegetyp = models.TextField()

    class Meta:
        db_table = 'lt_pflegetyp'

    def __str__(self):
        return self.pflegetyp


class Pflege(gis_models.Model):
    gid = models.AutoField(primary_key=True)
    id  = models.IntegerField(unique=True, null=True, blank=True)
    the_geom = gis_models.PolygonField(srid=2056)
    lokalname = models.TextField(blank=True)
    geplant = models.ForeignKey(EingriffsJahr, blank=True, null=True,
        db_column='eingriffsjahr_geplant', related_name='geplant_pflege',
        verbose_name="Pflege geplant", on_delete=models.CASCADE)
    pflegeziel = models.TextField(blank=True)
    pflegetyp = models.ForeignKey(PflegeTyp, db_column='pflegetyp', on_delete=models.CASCADE)
    bestockungsziel = models.TextField(blank=True)
    gesuchnummer = models.IntegerField(null=True, blank=True)
    bemerkungen = models.TextField(db_column="bemerkungen, Besonderheiten", blank=True)
    auszahlungsbetrag = models.IntegerField(null=True, blank=True)
    ansatz_pflegeeingriff = models.IntegerField(null=True, blank=True,
        verbose_name="Ansatz Pflegeeingriff")
    naechster_eingriff = models.IntegerField(null=True, blank=True, verbose_name="Nächster Eingriff",
        help_text="Nächster Eingriff vorgesehen im Jahr 20?? (z.b. \"2020\")")
    neigung = models.BooleanField(default=False, help_text="angekreuzt: Neigung >50%")
    baumart = models.BooleanField(default=False, help_text="angekreuzt: Fi, Ta, Dgl, Lä")
    wertastung = models.BooleanField(default=False, help_text="angekreuzt: Wertastung vorgesehen")
    eigentum = models.ForeignKey(Eigentuemer, db_column='eigentum', on_delete=models.CASCADE)
    ver_person = models.TextField(blank=True, verbose_name="Verantwortliche Person")

    class Meta:
        db_table = 'massnahme_pflege'

    def __str__(self):
        return "-".join([self.eigentum.name, self.lokalname or '', self.pflegeziel or ''])

    @property
    def title(self):
        return f"{self.pflegetyp}: {self.lokalname} ({self.geplant}); {self.eigentum}"

    def get_absolute_url(self):
        return reverse('pflege_detail', args=[self.pk])


class Naturschutzgebiet(gis_models.Model):
    SCHUTZ_CHOICES = (
        ('kantonal', 'kantonal'),
        ('kommunal', 'kommunal'),
    )
    lokalname = models.CharField(max_length=200)
    geom = gis_models.MultiPolygonField(srid=2056)
    schutzstatus = models.CharField(max_length=10, choices=SCHUTZ_CHOICES)
    schutzziel = models.TextField()

    class Meta:

unterhalt/models.py
from datetime import date
from django.contrib.gis.db import models as gis_models
from django.db import models
from django.urls import reverse

from massnahmen.models import Eigentuemer


class Einrichtungsart(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'lt_einrichtungsart'

    def __str__(self):
        return self.name


class Eigentuemertyp(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'lt_eigentuemertyp'

    def __str__(self):
        return self.name


class Kontaktperson(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(blank=True)
    tel = models.CharField(max_length=25, blank=True)

    class Meta:
        db_table = 'lt_kontaktperson'

    def __str__(self):
        return self.name

    def full(self):
        """Return "name (tel, email)"."""
        full_name = self.name
        if self.email or self.tel:
            full_name = '{} ({})'.format(
                full_name, ', '.join([el for el in [self.tel, self.email] if el])
            )
        return full_name


class Freizeiteinrichtung(gis_models.Model):
    gid = models.AutoField(primary_key=True)
    name = models.CharField("Flurname", max_length=30, blank=True, db_column='objektname')
    beschreibung = models.CharField(max_length=80, blank=True)
    obj_art = models.ForeignKey(Einrichtungsart, on_delete=models.CASCADE, verbose_name="Objekttyp")
    werkeigentuemer = models.ForeignKey(Eigentuemertyp, on_delete=models.CASCADE)
    waldbesitzer = models.ForeignKey(Eigentuemer, on_delete=models.CASCADE)
    kontaktperson = models.ForeignKey(Kontaktperson, on_delete=models.CASCADE)
    unterhaltsmassnahmen = models.TextField(blank=True)
    bemerkung_unterhalt = models.TextField(blank=True)
    laufender_unterhalt = models.BooleanField(default=False)
    periodischer_unterhalt = models.BooleanField(default=False)
    foto = models.ImageField("Foto", upload_to='fotos', blank=True)

    the_geom = gis_models.PointField(srid=2056, null=True, verbose_name="Standort")

    class Meta:
        db_table = 'freizeiteinrichtungen'

    def __str__(self):
        return self.name or self.beschreibung or (
            self.obj_art.name if self.obj_art_id else 'unbekannt Einrichtung'
        )

    @property
    def title(self):
        return str(self)

    def get_absolute_url(self):
        return '%s#%d' % (reverse('freizeit-map'), self.pk)


UMSETZUNG_CHOICES = (
    (1, "Objektbesitzer"),
    (2, "Forstbetrieb"),
    (3, "Baumpfleger"),
    (4, "Einwohnergemeinde"),
)

class Unterhalt(models.Model):
    # datum/erledigt as DateTime Field because of a bug in QGIS Offline plugin
    objekt = models.ForeignKey(Freizeiteinrichtung, on_delete=models.CASCADE)
    datum = models.DateTimeField()
    kein_unterhalt = models.BooleanField("kein Unterhalt nötig", default=False,
        help_text="keine Unterhaltsmassnahmen am Objekt und am Baumbestand nötig")
    unterhalt_objekt = models.BooleanField("Unterhalt Object", default=True)
    massnahme_objekt = models.TextField("Massnahmen an der Erholungseinrichtung (Objekt)", blank=True)
    unterhalt_baumbestand = models.BooleanField("Unterhalt Baumbestand", default=False)
    massnahmen_baumbestand = models.TextField("Massnahmen am Baumbestand", blank=True)
    umsetzung = models.IntegerField(null=True, blank=True, choices=UMSETZUNG_CHOICES,
        help_text="Unterhaltsarbeiten auszuführen durch")
    erledigt = models.DateTimeField(null=True, blank=True,
        help_text="Unterhaltsarbeiten erledigt am (Datum)")
    foto = models.ImageField("Foto", upload_to='fotos', blank=True)

    class Meta:
        db_table = 'unterhalt'
        ordering = ('-datum',)

    def __str__(self):
        return "%s für %s (%s)" % (self.massnahme_objekt, self.objekt, self.datum)

    @property
    def editable(self):
        return self.datum.year >= date.today().year


class Belegung(models.Model):
    objekt = models.ForeignKey(Freizeiteinrichtung, on_delete=models.CASCADE)
    schulklasse = models.TextField()
    infrastruktur = models.TextField(blank=True)
    bemerkungen = models.TextField(blank=True)
    einzeltage = models.DateTimeField(null=True, blank=True)
    wochentage = models.TextField(blank=True)
    verant_person = models.TextField(),
    tel_verant_pers = models.CharField("Telefon verantwortliche Person", max_length=100, blank=True)
    email_verant_pers = models.CharField("Email verantwortliche Person", max_length=200, blank=True)

    class Meta:
        db_table = 'lt_belegung'

    def __str__(self):
        return "{} ({})".format(self.schulklasse, self.wann)

    @property
    def wann(self):
        return self.einzeltage.strftime('%d.%m.%Y') if self.einzeltage else self.wochentage

templates/base_list.html
{% extends "base.html" %}

{% block extra_head %}
<script type="text/javascript" src="{{ STATIC_URL }}js/tablesorter/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/tablesorter/js/jquery.tablesorter.widgets.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $("table").tablesorter({
      widgets: ["filter"]
    });
    $("a#csv_export").on("click", function(ev) {
        // Intercept export click and append selected ids to the GET request
        ev.preventDefault();
        var ids = $("table.list tr.data:visible").map(function() { return this.id; }).get().join();
        window.location = this.href + '?ids=' + ids;
    });
  });
</script>
<style>
td.right { text-align:right; }
tr.tablesorter-filter input { width: 8em; }
</style>
{% endblock %}

{% block content_footer %}
<div style="margin-top: 0.4em;">
  <a id="csv_export" class="icon" href="export/"><img src="{{ STATIC_URL }}img/csv_icon.gif" title="CSV export"></a>
</div>
{% endblock %}

templates/freizeit_details.html
{% load static %}
<h2>{{ object }}</h2>

<table class="list">
    {% if object.beschreibung %}<tr><th>Beschreibung</th><td>{{ object.beschreibung }}</td></tr>{% endif %}
    <tr><th>Einrichtungsart</th><td>{{ object.obj_art }}</td></tr>
    <tr><th>Eigentuemer</th><td>{{ object.waldbesitzer }}</td></tr>
    <tr><th>Eigentuemertyp</th><td>{{ object.werkeigentuemer }}</td></tr>
    <tr><th>Kontaktperson</th><td>{{ object.kontaktperson.full }}</td></tr>
    <tr><th>Unterhaltsmassnahmen</th><td>{{ object.unterhaltsmassnahmen|default_if_none:'-' }}</td></tr>
    <tr><th>Bemerkungen</th><td>{{ object.bemerkung_unterhalt|default_if_none:'-' }}</td></tr>
</table>
<div style="text-align: right;">
    <a class="icon" href="{% url 'freizeit-edit' object.pk %}" title="Freizeiteinrichtung bearbeiten"><img src="{% static 'img/edit.png' %}" width="28"></a>
    <form style="display:inline;" method="post" action="{% url 'freizeit-delete' object.pk %}"
          data-confirm="Möchten Sie dieses Objekt wirklich löschen?">{% csrf_token %}
        <input src="{% static 'img/delete.svg' %}" title="Freizeiteinrichtung löschen" type="image" width="24" height="24">
    </form>
</div>

<h4 class="subsection">Massnahmen</h4>
<ul class="smallmargins">
{% for unterhalt in object.unterhalt_set.all %}
    {% if unterhalt.erledigt %}
        <li class="erledigt">{{ unterhalt.datum|date:'j.m.Y' }}: {{ unterhalt.massnahme_objekt }}, erledigt am {{ unterhalt.erledigt }}
    {% elif unterhalt.kein_unterhalt %}
        <li>{{ unterhalt.datum|date:'j.m.Y' }}: <i>Kein Unterhalt nötig</i>
    {% else %}
        <li>{{ unterhalt.datum|date:'j.m.Y' }}: {{ unterhalt.massnahme_objekt }}
    {% endif %}
    {% if unterhalt.foto %}
        <a class="icon" href="{{ unterhalt.foto.url }}"><img src="{% static 'img/generic_img.png' %}" width="32"></a>
    {% endif %}
    {% if unterhalt.editable %}
        {% if not unterhalt.kein_unterhalt %}
        <a class="icon" href="{% url 'massnahme-edit' unterhalt.pk %}"
                     title="Dieses Objekt bearbeiten">
                  <img src="{% static 'img/edit.png' %}" width="14"></a>
        {% endif %}
    <form style="display:inline;" method="post" action="{% url 'massnahme-delete' unterhalt.pk %}"
          data-confirm="Möchten Sie dieses Objekt wirklich löschen?">{% csrf_token %}
        <input src="{% static 'img/delete.svg' %}" title="Massnahme löschen" type="image" style="vertical-align: bottom;" width="14" height="14">
    </form>
    {% endif %}
    </li>
{% empty %}
  <li><i>Keine</i></li>
{% endfor %}
</ul>
<div style="text-align: right;">
    <i><small><a href="{% url 'massnahme-add' object.pk %}">Massnahme hinzufügen…</a></small></i>
</div>

<h4 class="subsection">Belegung</h4>
<ul class="smallmargins">
{% for belegung in object.belegung_set.all %}
    <li><span class="belegung-title" title="Klicken Sie um mehr Details zu sehen">{{ belegung }}</span>
        <a class="icon" href="{% url 'belegung-edit' belegung.pk %}"
           title="Dieses Objekt bearbeiten">
           <img src="{% static 'img/edit.png' %}" width="14"></a>
        <form style="display:inline;" method="post" action="{% url 'belegung-delete' belegung.pk %}"
              data-confirm="Möchten Sie dieses Objekt wirklich löschen?">{% csrf_token %}
            <input src="{% static 'img/delete.svg' %}" title="Belegung löschen" type="image" width="14" height="14">
        </form>
        <div class="details-hidden">
            {% if belegung.infrastruktur %}<b>Infrastruktur:</b> {{ belegung.infrastruktur }}<br>{% endif %}
            {% if belegung.bemerkungen %}<b>Bemerkungen:</b> {{ belegung.bemerkungen }}<br>{% endif %}
            {% if belegung.tel_verant_pers %}<b>Tel. verantw. Person:</b> {{ belegung.tel_verant_pers }}<br>{% endif %}
            {% if belegung.email_verant_pers %}<b>Email verantw. Person:</b> {{ belegung.email_verant_pers }}<br>{% endif %}
        </div>
    </li>
{% empty %}
  <li><i>Keine</i></li>
{% endfor %}
</ul>
<div style="text-align: right;">
    <i><small><a href="{% url 'belegung-add' object.pk %}">Belegung hinzufügen…</a></small></i>
</div>

{% if object.foto %}
<div class="image">
    <img src="{{ object.foto.url }}" style="max-width: 100%">
</div>
{% endif %}

templates/freizeit_edit.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
{% include "map_headers.html" %}
{{ form.media }}
<style>
    div.label { font-size: small; font-weight: bold; }
    div.input { margin-bottom: 0.7em; clear: left; }
    input[type=text] { min-width: 40em; }
    textarea { min-width: 40em; height: 4em; }
    span.clear_features { font-size: small; }
</style>
{% endblock %}

{% block content %}
<h2>Freizeiteinrichtung bearbeiten</h2>
<form method="post" enctype="multipart/form-data" action=".">{% csrf_token %}
  {% for field in form %}
  <div class="label">{{ field.label_tag }} {{ field.errors }}</div>
  <div class="input">{{ field }}
    {% if field.name == 'obj_art' and perms.unterhalt.change_einrichtungsart %}
        <a class="icon" href="{% url 'admin:unterhalt_einrichtungsart_changelist' %}" title="Objekttype bearbeiten" target="_blank">
        <img src="{% static 'img/edit.png' %}" width="28"></a>
    {% endif %}
    {% if field.name == 'werkeigentuemer' and perms.unterhalt.change_eigentuemertyp %}
        <a class="icon" href="{% url 'admin:unterhalt_eigentuemertyp_changelist' %}" title="Eigentuemertype bearbeiten" target="_blank">
        <img src="{% static 'img/edit.png' %}" width="28"></a>
    {% endif %}
    {% if field.name == 'waldbesitzer' and perms.massnahmen.change_eigentuemer %}
        <a class="icon" href="{% url 'admin:massnahmen_eigentuemer_changelist' %}" title="Eigentuemer bearbeiten" target="_blank">
        <img src="{% static 'img/edit.png' %}" width="28"></a>
    {% endif %}
    {% if field.name == 'kontaktperson' and perms.unterhalt.change_kontaktperson %}
        <a class="icon" href="{% url 'admin:unterhalt_kontaktperson_changelist' %}" title="Kontaktpersonen bearbeiten" target="_blank">
        <img src="{% static 'img/edit.png' %}" width="28"></a>
    {% endif %}
    {% if field.name == 'foto' and form.instance.foto %}
        <div><img style="max-height: 160px;" src="{{ form.instance.foto.url }}"></div>
    {% endif %}
  </div>
  {% endfor %}
  <div class="input">
      <button type="submit">Speichern</button>
      <button class="cancel" type="button" onclick="window.history.back();">Abbrechen</button>
  </div>
</form>
{% endblock %}

templates/unterhalt_edit.html
{% extends "base.html" %}
{% load common %}

{% block extra_head %}
{{ form.media }}
<style>
textarea { height: 3em; }
div.label, span.label { font-size: small; font-weight: bold; }
label.disabled { color: gray; font-style: italic; }
div.input { margin-bottom: 0.7em; clear: left; }
button.cancel { margin-left: 3em; }
</style>

<script type="text/javascript">
$(document).ready(function() {
    $('#id_kein_unterhalt').change(function(ev) {
        var checked = $(this).is(":checked");
        var whitelist = ['id_kein_unterhalt', 'id_datum', 'id_objekt'];
        $(this.form).find("input, select, textarea").each(function() {
            if (this.name != 'csrfmiddlewaretoken' && whitelist.indexOf(this.id) == -1) {
                if (checked) {
                    $('#id_unterhalt_objekt').prop('checked', false);
                    $(this).prop('disabled', true);
                    $("label[for='" + this.id + "']").addClass('disabled');
                } else {
                    $(this).prop('disabled', false);
                    $("label[for='" + this.id + "']").removeClass('disabled');
                    $('#id_unterhalt_objekt').prop('checked', true);
                }
            }
        });
    });
});
</script>
{% endblock %}

{% block content %}
<h2>{% if form.instance.pk %}Massnahme bearbeiten{% else %}Massnahme erfassen{% endif %}</h2>

<p>Mit diesem Formular kann eine Unterhaltsmassnahme für ein Erholungsobjekt und/oder den umliegende Baumbestand erfasst werden.<br>
Es kann auch dokumentiert werden, dass zu diesem Zeitpunkt keine Massnahmen notwenig sind ("Kein Unterhalt nötig" Kästchen).
</p>

<p>Freizeiteinrichtung: {% if form.instance.pk %}{{ form.instance.objekt }}{% else %}{{ form.initial.objekt }}{% endif %}</p>

<form method="post" enctype="multipart/form-data" action=".">{% csrf_token %}
  {% for field in form.visible_fields %}
    {% if field|is_checkbox %}
      <div class="input">
          {{ field.errors }} {{ field }} <span class="label">{{ field.label_tag|strip_colon }}</span>
          {% if field.help_text %}<br><span class="help_text">{{ field.help_text }}</span>{% endif %}
      </div>
    {% else %}
      <div class="label">
        {{ field.label_tag }} {{ field.errors }}
        {% if field.help_text %}<span class="help_text">{{ field.help_text }}</span>{% endif %}
      </div>
      <div class="input">{{ field }}</div>
    {% endif %}
  {% endfor %}
  {% for field in form.hidden_fields %}{{ field }}{% endfor %}
  <div class="input">
      <button type="submit">Speichern</button>
      <button class="cancel" type="button" onclick="window.history.back();">Abbrechen</button>
  </div>
</form>
{% endblock %}